version: "2.2"

services:
  journal:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: journal
    networks:
      - test-network

  journal_postgres:
    image: postgres:9.5
    container_name: postgres.journal
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: journal
      POSTGRES_USER: journal
      POSTGRES_PASSWORD: journal
    networks:
      - test-network

networks:
  test-network:
    driver: bridge