version: "2.2"

services:
  journal:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: journal
    environment:
      RAVEN_CONFIG_DSN: "YOUR_DSN_HERE"
      RAVEN_CONFIG_RELEASE: "dev"
      ENABLE_RAVEN: "False"
    ports:
      - "8000"

  journal_postgres:
    image: postgres:9.5
    container_name: postgres.journal
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: journal
      POSTGRES_USER: journal
      POSTGRES_PASSWORD: journal
