version: "2"

services:
  journal:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: journal
    environment:
      DJANGO_CONFIGURATION: Production
    networks:
      - ${COMPOSE_PROJECT_NAME}-network

  journal_postgres:
      image: postgres:9.5
      container_name: postgres.journal
      volumes:
        - ./postgres/${CONTAINER_NAME}/data:/var/lib/postgresql/data
        - ./postgres/${CONTAINER_NAME}/conf:/etc/postgresql
        - ./postgres/${CONTAINER_NAME}/logs:/var/log/postgresql
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_DB: journal
        POSTGRES_USER: journal
        POSTGRES_PASSWORD: journal

      networks:
        - ${COMPOSE_PROJECT_NAME}-network