# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='objects', max_length=255)),
                ('history_record_key', models.CharField(default='pk', max_length=255)),
                ('history_record_actor', models.CharField(default='actor.id', max_length=255)),
                ('save_diff', models.BooleanField(default=True)),
            ],
        ),
    ]
