# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 14:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', django.contrib.postgres.fields.jsonb.JSONField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('diff', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='objects', max_length=255)),
                ('history_record_key', models.CharField(default='pk', max_length=255)),
                ('history_record_actor', models.CharField(default='actor.id', max_length=255)),
                ('save_diff', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='api.Journal'),
        ),
    ]
