# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_historyrecord_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='alias',
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
