# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180621_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='prev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HistoryRecord'),
        ),
    ]
