# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historyrecord_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='owner',
            field=models.IntegerField(default=None, null=True, verbose_name='Owner'),
        ),
    ]
